// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDisplayGroups() {
  return window['go']['keycodes']['KeycodeHelper']['GetDisplayGroups']();
}

export function GetJSCodeGroups() {
  return window['go']['keycodes']['KeycodeHelper']['GetJSCodeGroups']();
}

export function GetRawcodeGroups() {
  return window['go']['keycodes']['KeycodeHelper']['GetRawcodeGroups']();
}
