// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {keycodes} from '../models';

export function GetDisplayGroups():Promise<Record<keycodes.KeycodeGroup, Record<string, keycodes.Keycode>>>;

export function GetJSCodeGroups():Promise<Record<keycodes.KeycodeGroup, Record<string, keycodes.Keycode>>>;

export function GetRawcodeGroups():Promise<Record<keycodes.KeycodeGroup, Record<number, keycodes.Keycode>>>;
