// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeycodes() {
  return window['go']['keycodes']['KeycodeHelper']['GetKeycodes']();
}

export function RawcodeToString(arg1) {
  return window['go']['keycodes']['KeycodeHelper']['RawcodeToString'](arg1);
}

export function StringToRawcode(arg1) {
  return window['go']['keycodes']['KeycodeHelper']['StringToRawcode'](arg1);
}
