// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetKeycodes():Promise<Record<number, string>>;

export function RawcodeToString(arg1:number):Promise<string>;

export function StringToRawcode(arg1:string):Promise<number>;
