// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSounds() {
  return window['go']['app']['App']['AddSounds']();
}

export function ClearHotkey(arg1) {
  return window['go']['app']['App']['ClearHotkey'](arg1);
}

export function ClearStopHotkey() {
  return window['go']['app']['App']['ClearStopHotkey']();
}

export function ErrorDialog(arg1) {
  return window['go']['app']['App']['ErrorDialog'](arg1);
}

export function GetPlaybackDeviceInfo() {
  return window['go']['app']['App']['GetPlaybackDeviceInfo']();
}

export function GetSoundHotkeys() {
  return window['go']['app']['App']['GetSoundHotkeys']();
}

export function GetStopHotkey() {
  return window['go']['app']['App']['GetStopHotkey']();
}

export function LoadSoundboard() {
  return window['go']['app']['App']['LoadSoundboard']();
}

export function PlaySound(arg1) {
  return window['go']['app']['App']['PlaySound'](arg1);
}

export function RemoveSound(arg1) {
  return window['go']['app']['App']['RemoveSound'](arg1);
}

export function ResetSoundboard() {
  return window['go']['app']['App']['ResetSoundboard']();
}

export function SaveSoundboard() {
  return window['go']['app']['App']['SaveSoundboard']();
}

export function SetHotkey(arg1, arg2) {
  return window['go']['app']['App']['SetHotkey'](arg1, arg2);
}

export function SetPlaybackDevice(arg1) {
  return window['go']['app']['App']['SetPlaybackDevice'](arg1);
}

export function SetStopHotkey(arg1) {
  return window['go']['app']['App']['SetStopHotkey'](arg1);
}

export function StopAllSounds() {
  return window['go']['app']['App']['StopAllSounds']();
}
