// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSounds() {
  return window['go']['main']['App']['AddSounds']();
}

export function ClearHotkey(arg1) {
  return window['go']['main']['App']['ClearHotkey'](arg1);
}

export function ClearStopHotkey() {
  return window['go']['main']['App']['ClearStopHotkey']();
}

export function GetPlaybackDeviceInfo() {
  return window['go']['main']['App']['GetPlaybackDeviceInfo']();
}

export function GetSoundHotkeys() {
  return window['go']['main']['App']['GetSoundHotkeys']();
}

export function GetStopHotkey() {
  return window['go']['main']['App']['GetStopHotkey']();
}

export function PlaySound(arg1) {
  return window['go']['main']['App']['PlaySound'](arg1);
}

export function RemoveSound(arg1) {
  return window['go']['main']['App']['RemoveSound'](arg1);
}

export function SetHotkey(arg1, arg2) {
  return window['go']['main']['App']['SetHotkey'](arg1, arg2);
}

export function SetPlaybackDevice(arg1) {
  return window['go']['main']['App']['SetPlaybackDevice'](arg1);
}

export function SetStopHotkey(arg1) {
  return window['go']['main']['App']['SetStopHotkey'](arg1);
}

export function ShowDialog(arg1) {
  return window['go']['main']['App']['ShowDialog'](arg1);
}

export function StopAllSounds() {
  return window['go']['main']['App']['StopAllSounds']();
}
