// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlaybackDeviceInfo() {
  return window['go']['main']['App']['GetPlaybackDeviceInfo']();
}

export function GetSoundHotkeys() {
  return window['go']['main']['App']['GetSoundHotkeys']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PlaySound(arg1) {
  return window['go']['main']['App']['PlaySound'](arg1);
}

export function SetPlaybackDevice(arg1) {
  return window['go']['main']['App']['SetPlaybackDevice'](arg1);
}

export function SetSoundHotkeys(arg1) {
  return window['go']['main']['App']['SetSoundHotkeys'](arg1);
}

export function ShowDialog(arg1) {
  return window['go']['main']['App']['ShowDialog'](arg1);
}
