// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audiodevice} from '../models';
import {soundhotkey} from '../models';

export function AddSounds():Promise<void>;

export function ClearHotkey(arg1:string):Promise<void>;

export function ClearStopHotkey():Promise<void>;

export function ErrorDialog(arg1:string):Promise<void>;

export function GetPlaybackDeviceInfo():Promise<Array<audiodevice.AudioDevice>>;

export function GetSoundHotkeys():Promise<Array<soundhotkey.SoundHotkey>>;

export function GetStopHotkey():Promise<Array<number>>;

export function LoadSoundboard():Promise<void>;

export function PlaySound(arg1:string):Promise<void>;

export function RemoveSound(arg1:string):Promise<void>;

export function ResetSoundboard():Promise<void>;

export function SaveSoundboard():Promise<void>;

export function SetHotkey(arg1:string,arg2:Array<number>):Promise<void>;

export function SetPlaybackDevice(arg1:string):Promise<void>;

export function SetStopHotkey(arg1:Array<number>):Promise<void>;

export function ShowDialog(arg1:string):Promise<void>;

export function StopAllSounds():Promise<void>;
