name: Wails build

on:
  push:
    tags:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          # - name: 'Linux App'
          #   platform:  'linux/amd64'
          #   os: 'ubuntu-latest'
          - name: 'Windows App'
            platform:  'windows/amd64'
            os: 'windows-latest'
          # - name: 'Mac App'
          #   platform:  'darwin/universal'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      # - uses: shogo82148/actions-setup-perl@v1
      #   with:
      #     perl-version: "5.32"
      #     distribution: strawberry

      # - name: Set up MinGW
      #   uses: egor-tensin/setup-mingw@v2
      #   with:
      #     platform: x64

      - name: Check local
        run: |
          echo "$env:PATH"
          ls C:\Strawberry\perl\bin\pkg-config.bat
          $env:PATH = "C:\Strawberry\perl\bin\pkg-config.bat;$env:PATH"

      - name: Setup PortAudio
        run: |
          $env:PATH = "C:\msys64\usr\bin;$env:PATH"
          pacman --noconfirm -S mingw-w64-x86_64-portaudio

      - name: Setup PkgConfig (Windows)
        if: runner.os == 'Windows'
        env:
          PKG_CONFIG_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip"
          GETTEXT_RUNTIME_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip"
          GLIB_ZIP: "http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip"
        run: |
          curl -LO "${{ env.PKG_CONFIG_ZIP }}"
          7z x pkg-config_0.26-1_win32.zip -oC:\MinGW\bin pkg-config.exe
          curl -LO "${{ env.GETTEXT_RUNTIME_ZIP }}"
          7z x gettext-runtime_0.18.1.1-2_win32.zip -oC:\MinGW\bin intl.dll
          curl -LO "${{ env.GLIB_ZIP }}"
          7z x glib_2.28.8-1_win32.zip -oC:\MinGW\bin libglib-2.0-0.dll
          echo "C:\MinGW\bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check local Again
        run: |
          echo "$env:PATH"
          ls C:\Strawberry\perl\bin\pkg-config.bat

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.24'
          # wails-version: "v2.9.0"